#!/usr/bin/env bash
# =============================================================================
#  start_soc_stack.sh — starts the whole SOC stack on the Dell Pro Max GB10
#
#    1. llama-server (router mode, several models) on 127.0.0.1:8000
#    2. NemoClaw: OpenShell sandbox + Slack channel
#    3. OpenClaw agent: version check, SOC instructions, test turn
#    4. health checks (sandbox, Slack)
#
#  Usage:
#    cp scripts/soc-stack.env.example ~/soc-stack.env   # then fill in the Slack tokens
#    bash scripts/start_soc_stack.sh                    # start everything
#    bash scripts/start_soc_stack.sh stop               # stop llama-server and the sandbox
#    bash scripts/start_soc_stack.sh status             # show stack status
#    bash scripts/start_soc_stack.sh analyze [log]      # one OpenClaw analysis, result posted to Slack
#
#  References: NemoClaw docs (inference/set-up-openai-compatible-endpoint,
#  manage-sandboxes/set-up-slack, reference/commands) shipped in 01_nemoclaw/.
# =============================================================================
set -euo pipefail

KIT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${SOC_ENV_FILE:-$HOME/soc-stack.env}"
[ -f "$ENV_FILE" ] && { set -a; . "$ENV_FILE"; set +a; }

# ----------------------------- configuration ---------------------------------
# (every value below can be overridden in ~/soc-stack.env)
MODELS_DIR="${MODELS_DIR:-/home/dell/hktn}"                 # folder holding the GGUF files
LLAMA_SERVER="${LLAMA_SERVER:-$(command -v llama-server || echo "$HOME/llama.cpp/build/bin/llama-server")}"
LLAMA_PORT="${LLAMA_PORT:-8000}"                            # LLM server port (any free port except 11435; 127.0.0.1 only)
DASHBOARD_PORT="${DASHBOARD_PORT:-18789}"                   # OpenClaw web dashboard port (1024-65535)
# NEMOCLAW_GATEWAY_PORT=…                                   # optional: OpenShell gateway port (set only if the default is taken)
AGENT_MODEL="${AGENT_MODEL:-Qwen3.8-27B}"                   # model that drives the agent (must handle tool calling)
SANDBOX_NAME="${SANDBOX_NAME:-soc-agent}"
POLICY_TIER="${POLICY_TIER:-balanced}"                      # restricted | balanced | open
LOGS_DIR="${LOGS_DIR:-/var/log}"                            # mounted read-only at /sandbox/logs
RUN_DIR="${RUN_DIR:-$HOME/.soc-stack}"
# Slack (Socket Mode): SLACK_BOT_TOKEN (xoxb-…), SLACK_APP_TOKEN (xapp-…),
#                      SLACK_ALLOWED_USERS, SLACK_ALLOWED_CHANNELS (comma-separated IDs)
# -----------------------------------------------------------------------------

mkdir -p "$RUN_DIR"
say()  { printf '\n\033[1;32m== %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m!! %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31mXX %s\033[0m\n' "$*"; exit 1; }

# ------------------------------- models.ini ----------------------------------
write_models_ini() {
  cat > "$RUN_DIR/models.ini" <<EOF
; Generated by start_soc_stack.sh — llama-server router mode
[Qwen3.8-27B]
model = $MODELS_DIR/Qwen3.8-27B/Qwen3.8-27B-UD-Q6_K_XL.gguf
n-gpu-layers = 99
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0
ctx-size = 131072
fa = on
reasoning = on
sleep-idle-seconds = 600

[NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF]
model = $MODELS_DIR/Nemotron-3.5-Lightning/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-UD-Q4_K_XL.gguf
n-gpu-layers = 99
temp = 0.6
top-p = 0.95
min-p = 0.01
ctx-size = 262144
cache-type-k = q4_0
cache-type-v = q4_0
kv-unified = true
fa = on
reasoning = on
sleep-idle-seconds = 600
chat-template-kwargs = {"preserve_thinking": true}

[CyberPal2.0-20B]
model = $MODELS_DIR/CyberPal2.0-20B/gguf/CyberPal2.0-20B.MXFP4_MOE.gguf
n-gpu-layers = 99
temp = 0.2
top-p = 1.0
top-k = 0
min-p = 0.0
ctx-size = 32768
fa = on
reasoning = on
sleep-idle-seconds = 600
chat-template-kwargs = {"reasoning_effort": "medium"}
EOF
  # Drop presets whose GGUF file is missing
  python3 - "$RUN_DIR/models.ini" <<'PY'
import sys, re, os
p = sys.argv[1]; out = []; kept = []
for block in re.split(r'\n(?=\[)', open(p).read()):
    m = re.search(r'^model = (.+)$', block, re.M)
    if m and not os.path.isfile(m.group(1).strip()):
        print(f"   (skipped, file not found) {m.group(1).strip()}"); continue
    out.append(block); kept += re.findall(r'^\[(.+)\]', block, re.M)
open(p, 'w').write('\n'.join(out) + '\n')
print("   models served:", ", ".join(kept) or "NONE")
PY
}

# ------------------------------ llama-server ---------------------------------
check_ports() {
  [ "$LLAMA_PORT" = 11435 ] && die "LLAMA_PORT 11435 is reserved by NemoClaw's proxy"
  for p in "$DASHBOARD_PORT"; do
    if ss -ltn 2>/dev/null | awk '{print $4}' | grep -qE "[:.]$p$"; then
      warn "port $p is already in use (fine if it is this stack running already)"
    fi
  done
}

start_llama() {
  say "1/4  llama-server (router) on 127.0.0.1:$LLAMA_PORT"
  [ -x "$LLAMA_SERVER" ] || die "llama-server not found ($LLAMA_SERVER). Set LLAMA_SERVER in $ENV_FILE"
  if curl -sf "http://127.0.0.1:$LLAMA_PORT/health" >/dev/null 2>&1; then
    echo "   already running"; return
  fi
  write_models_ini
  # 127.0.0.1 is required: NemoClaw rejects a no-auth backend exposed on 0.0.0.0
  nohup "$LLAMA_SERVER" --models-preset "$RUN_DIR/models.ini" \
        --host 127.0.0.1 --port "$LLAMA_PORT" ${LLAMA_EXTRA_ARGS:-} \
        > "$RUN_DIR/llama-server.log" 2>&1 &
  echo $! > "$RUN_DIR/llama-server.pid"
  printf "   starting"
  for _ in $(seq 1 120); do
    curl -sf "http://127.0.0.1:$LLAMA_PORT/health" >/dev/null 2>&1 && { echo " OK"; break; }
    kill -0 "$(cat "$RUN_DIR/llama-server.pid")" 2>/dev/null || { echo; tail -20 "$RUN_DIR/llama-server.log"; die "llama-server exited"; }
    printf "."; sleep 2
  done
  curl -sf "http://127.0.0.1:$LLAMA_PORT/v1/models" | python3 -c \
    "import json,sys;print('   /v1/models:', [m['id'] for m in json.load(sys.stdin)['data']])"
  curl -sf "http://127.0.0.1:$LLAMA_PORT/v1/models" | grep -q "\"$AGENT_MODEL\"" \
    || die "AGENT_MODEL='$AGENT_MODEL' is not served. Check its GGUF file or change AGENT_MODEL."
  echo "   test generation with $AGENT_MODEL (first load can take 1-2 min)…"
  curl -sf -m 300 "http://127.0.0.1:$LLAMA_PORT/v1/chat/completions" -H 'content-type: application/json' \
    -d "{\"model\":\"$AGENT_MODEL\",\"messages\":[{\"role\":\"user\",\"content\":\"Reply with OK\"}],\"max_tokens\":256}" \
    >/dev/null && echo "   generation OK" || warn "test generation failed (see $RUN_DIR/llama-server.log)"
}

# -------------------------------- NemoClaw -----------------------------------
start_nemoclaw() {
  say "2/4  NemoClaw: sandbox '$SANDBOX_NAME' (OpenShell + OpenClaw + Slack)"
  command -v nemoclaw >/dev/null || die "nemoclaw not found: run  bash 01_nemoclaw/nemoclaw.sh  first"
  command -v docker  >/dev/null || die "docker not found"

  if nemoclaw "$SANDBOX_NAME" status >/dev/null 2>&1; then
    echo "   sandbox already exists → starting it"
    nemoclaw "$SANDBOX_NAME" start || true
    return
  fi

  if [ -n "${SLACK_BOT_TOKEN:-}" ] && [ -n "${SLACK_APP_TOKEN:-}" ]; then
    echo "   Slack: enabled (Socket Mode)"
    export SLACK_BOT_TOKEN SLACK_APP_TOKEN SLACK_ALLOWED_USERS="${SLACK_ALLOWED_USERS:-}" SLACK_ALLOWED_CHANNELS="${SLACK_ALLOWED_CHANNELS:-}"
  else
    warn "SLACK_BOT_TOKEN / SLACK_APP_TOKEN missing: the sandbox will be created without Slack"
  fi

  MOUNTS=()
  [ -d "$LOGS_DIR" ] && MOUNTS+=(--host-mount "$(realpath "$LOGS_DIR"):/sandbox/logs")
  [ -d "$KIT/06_mitre_attack" ] && MOUNTS+=(--host-mount "$KIT/06_mitre_attack:/sandbox/mitre")

  NEMOCLAW_AGENT=openclaw \
  NEMOCLAW_SANDBOX_NAME="$SANDBOX_NAME" \
  NEMOCLAW_PROVIDER=custom \
  NEMOCLAW_ENDPOINT_URL="http://localhost:$LLAMA_PORT/v1" \
  NEMOCLAW_MODEL="$AGENT_MODEL" \
  NEMOCLAW_COMPATIBLE_AUTH_MODE=none \
  NEMOCLAW_VLLM_PORT="$LLAMA_PORT" \
  NEMOCLAW_POLICY_TIER="$POLICY_TIER" \
    nemoclaw onboard --non-interactive --yes-i-accept-third-party-software --control-ui-port "$DASHBOARD_PORT" "${MOUNTS[@]}"
}

# -------------------------------- OpenClaw -----------------------------------
# OpenClaw runs INSIDE the OpenShell sandbox created by NemoClaw (NEMOCLAW_AGENT=openclaw).
# It is not a separate host process: you reach it through `nemoclaw <sandbox> exec|agent|launch`.
SOC_PROMPT='You are the SOC analyst agent. Security logs are mounted read-only in /sandbox/logs and the MITRE ATT&CK index is in /sandbox/mitre/techniques_index.json.
For every analysis:
1. Read only the relevant log lines (filter first, never load whole files).
2. Decide whether the activity is an attack (true/false).
3. Give a severity: low, medium, high or critical. Low = recon or a single failed attempt. Medium = repeated attempts, no success. High = successful access or execution on one host. Critical = credential theft, ransomware or lateral spread.
4. List MITRE ATT&CK technique IDs and check each one exists in /sandbox/mitre/techniques_index.json.
5. Quote the evidence log lines you used.
6. Give remediation steps in three groups: contain, eradicate, prevent.
Answer in English. Start with one line: "<SEVERITY> | <short title>". Never claim an action was executed: you only recommend, the analyst approves.'

setup_openclaw() {
  say "3/4  OpenClaw agent (inside sandbox '$SANDBOX_NAME')"
  echo -n "   OpenClaw version: "
  nemoclaw "$SANDBOX_NAME" exec -- openclaw --version 2>/dev/null || warn "could not read the OpenClaw version"

  # SOC instructions: written to the agent workspace and referenced from AGENTS.md
  printf '%s\n' "# SOC analyst role" "" "$SOC_PROMPT" > "$RUN_DIR/SOC_ANALYST.md"
  nemoclaw "$SANDBOX_NAME" upload "$RUN_DIR/SOC_ANALYST.md" /sandbox/.openclaw/workspace/SOC_ANALYST.md \
    && nemoclaw "$SANDBOX_NAME" exec --workdir /sandbox/.openclaw/workspace -- sh -c \
       'grep -q SOC_ANALYST.md AGENTS.md 2>/dev/null || printf "\n## SOC role\nRead and follow SOC_ANALYST.md for every security analysis.\n" >> AGENTS.md' \
    && echo "   SOC instructions installed (workspace/SOC_ANALYST.md)" \
    || warn "could not install SOC instructions"

  echo "   test turn through OpenClaw → $AGENT_MODEL …"
  nemoclaw "$SANDBOX_NAME" agent --agent main -m "Reply with exactly: OPENCLAW OK" --timeout 300 \
    | tail -3 || warn "OpenClaw test turn failed: nemoclaw $SANDBOX_NAME logs"
}

# One-shot analysis: OpenClaw reads a log file and delivers its report to Slack.
# Check the --to format for Slack with:  nemoclaw <sandbox> exec -- openclaw agent --help
analyze() {
  local log="${1:-auth.log}"
  local to="${SLACK_DELIVER_TO:-${SLACK_ALLOWED_CHANNELS%%,*}}"
  local msg="Analyze /sandbox/logs/$log for the last hour following SOC_ANALYST.md. Is it an attack? Severity, ATT&CK IDs, evidence lines, remediation."
  say "OpenClaw analysis of /sandbox/logs/$log"
  if [ -n "$to" ]; then
    nemoclaw "$SANDBOX_NAME" agent --agent main -m "$msg" --deliver --reply-channel slack --to "$to" --timeout 600
  else
    warn "no Slack channel set: printing the report here only"
    nemoclaw "$SANDBOX_NAME" agent --agent main -m "$msg" --timeout 600
  fi
}

# --------------------------------- checks ------------------------------------
check_all() {
  say "4/4  Health checks"
  nemoclaw "$SANDBOX_NAME" status || warn "status failed: run  nemoclaw $SANDBOX_NAME doctor"
  if [ -n "${SLACK_BOT_TOKEN:-}" ]; then
    echo "   waiting for Slack to connect (up to 180 s)…"
    nemoclaw "$SANDBOX_NAME" channels status --channel slack --wait --timeout 180 --json >/dev/null \
      && echo "   Slack connected" || warn "Slack not ready: nemoclaw $SANDBOX_NAME channels status --channel slack"
  fi
  cat <<EOF

$(printf '\033[1;32m')Stack is up.$(printf '\033[0m')
  OpenClaw chat (TUI) : nemoclaw launch $SANDBOX_NAME
  OpenClaw one turn   : nemoclaw $SANDBOX_NAME agent --agent main -m "..."
  Analysis → Slack    : bash scripts/start_soc_stack.sh analyze auth.log
  Shell in sandbox    : nemoclaw $SANDBOX_NAME connect
  Dashboard           : port $DASHBOARD_PORT  (full URL: nemoclaw $SANDBOX_NAME dashboard-url)
  Models (local)      : http://127.0.0.1:$LLAMA_PORT/v1/models
  llama-server logs   : $RUN_DIR/llama-server.log

  Slack test: in the allowed channel, post
    @<bot-name> Analyze /sandbox/logs/auth.log for the last hour. Is it an attack? Give severity
    (low/medium/high/critical), MITRE ATT&CK IDs, evidence lines and remediation steps.
EOF
}

stop_all() {
  say "Stopping"
  [ -f "$RUN_DIR/llama-server.pid" ] && kill "$(cat "$RUN_DIR/llama-server.pid")" 2>/dev/null && echo "   llama-server stopped"
  rm -f "$RUN_DIR/llama-server.pid"
  nemoclaw "$SANDBOX_NAME" stop 2>/dev/null || true
}

case "${1:-start}" in
  start)  check_ports; start_llama; start_nemoclaw; setup_openclaw; check_all ;;
  analyze) analyze "${2:-auth.log}" ;;
  stop)   stop_all ;;
  status) curl -sf "http://127.0.0.1:$LLAMA_PORT/health" && echo " llama-server OK" || echo "llama-server KO"
          nemoclaw "$SANDBOX_NAME" status || true ;;
  *) echo "usage: $0 [start|stop|status|analyze [logfile]]"; exit 1 ;;
esac